# Generated by Django 5.2.2 on 2025-06-24 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_title_recipe_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "ordering": ("recipe", "ingredient"),
                "verbose_name": "Ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Время приготовления должно быть не меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Время приготовления должно быть не больше 32000"
                    ),
                ],
                verbose_name="Время приготовления (в минутах)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Количество должно быть не меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Количество должно быть не больше 32000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
